local DEVICE_INFO1_ARRAY = {}
DEVICE_INFO1_ARRAY.id = 502
DEVICE_INFO1_ARRAY.fields = {
             { "hours_0", "<I2" },
             { "pwm_lost_count_0", "<I2" },
             { "hours_1", "<I2" },
             { "pwm_lost_count_1", "<I2" },
             { "hours_2", "<I2" },
             { "pwm_lost_count_2", "<I2" },
             { "type_0", "<B" },
             { "year_0", "<B" },
             { "month_0", "<B" },
             { "day_0", "<B" },
             { "number_0", "<B" },
             { "hw_major_0", "<B" },
             { "hw_minor_0", "<B" },
             { "sw_major_0", "<B" },
             { "sw_minor_0", "<B" },
             { "minutes_0", "<B" },
             { "type_1", "<B" },
             { "year_1", "<B" },
             { "month_1", "<B" },
             { "day_1", "<B" },
             { "number_1", "<B" },
             { "hw_major_1", "<B" },
             { "hw_minor_1", "<B" },
             { "sw_major_1", "<B" },
             { "sw_minor_1", "<B" },
             { "minutes_1", "<B" },
             { "type_2", "<B" },
             { "year_2", "<B" },
             { "month_2", "<B" },
             { "day_2", "<B" },
             { "number_2", "<B" },
             { "hw_major_2", "<B" },
             { "hw_minor_2", "<B" },
             { "sw_major_2", "<B" },
             { "sw_minor_2", "<B" },
             { "minutes_2", "<B" },
             }
return DEVICE_INFO1_ARRAY
