local DEVICE_STATUS_ARRAY = {}
DEVICE_STATUS_ARRAY.id = 501
DEVICE_STATUS_ARRAY.fields = {
             { "baud_rate_0", "<I2" },
             { "speed_0", "<I2" },
             { "baud_rate_1", "<I2" },
             { "speed_1", "<I2" },
             { "baud_rate_2", "<I2" },
             { "speed_2", "<I2" },
             { "baud_rate_3", "<I2" },
             { "speed_3", "<I2" },
             { "baud_rate_4", "<I2" },
             { "speed_4", "<I2" },
             { "baud_rate_5", "<I2" },
             { "speed_5", "<I2" },
             { "fault_status_0", "<B" },
             { "control_mode_0", "<B" },
             { "reserved_0", "<B" },
             { "life_signal_0", "<B" },
             { "fault_status_1", "<B" },
             { "control_mode_1", "<B" },
             { "reserved_1", "<B" },
             { "life_signal_1", "<B" },
             { "fault_status_2", "<B" },
             { "control_mode_2", "<B" },
             { "reserved_2", "<B" },
             { "life_signal_2", "<B" },
             { "fault_status_3", "<B" },
             { "control_mode_3", "<B" },
             { "reserved_3", "<B" },
             { "life_signal_3", "<B" },
             { "fault_status_4", "<B" },
             { "control_mode_4", "<B" },
             { "reserved_4", "<B" },
             { "life_signal_4", "<B" },
             { "fault_status_5", "<B" },
             { "control_mode_5", "<B" },
             { "reserved_5", "<B" },
             { "life_signal_5", "<B" },
             }
return DEVICE_STATUS_ARRAY
