local DEVICE_INFO2_ARRAY = {}
DEVICE_INFO2_ARRAY.id = 503
DEVICE_INFO2_ARRAY.fields = {
             { "hours_3", "<I2" },
             { "pwm_lost_count_3", "<I2" },
             { "hours_4", "<I2" },
             { "pwm_lost_count_4", "<I2" },
             { "hours_5", "<I2" },
             { "pwm_lost_count_5", "<I2" },
             { "type_3", "<B" },
             { "year_3", "<B" },
             { "month_3", "<B" },
             { "day_3", "<B" },
             { "number_3", "<B" },
             { "hw_major_3", "<B" },
             { "hw_minor_3", "<B" },
             { "sw_major_3", "<B" },
             { "sw_minor_3", "<B" },
             { "minutes_3", "<B" },
             { "type_4", "<B" },
             { "year_4", "<B" },
             { "month_4", "<B" },
             { "day_4", "<B" },
             { "number_4", "<B" },
             { "hw_major_4", "<B" },
             { "hw_minor_4", "<B" },
             { "sw_major_4", "<B" },
             { "sw_minor_4", "<B" },
             { "minutes_4", "<B" },
             { "type_5", "<B" },
             { "year_5", "<B" },
             { "month_5", "<B" },
             { "day_5", "<B" },
             { "number_5", "<B" },
             { "hw_major_5", "<B" },
             { "hw_minor_5", "<B" },
             { "sw_major_5", "<B" },
             { "sw_minor_5", "<B" },
             { "minutes_5", "<B" },
             }
return DEVICE_INFO2_ARRAY
